spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gs_reservation
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
